static const char* const TEXT_EMPTY = "";
static const char* const TEXT_SHORT = "test short text, test number 1 named short text aa";

static const char* const TEXT_BEST_CASE = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";

// TODO:
// - Add bigger tests
// - Add other languages tests
// - Add worst case scenario

static const char* const TEXT_1 = 
"In computer science and information theory, a Huffman code is a particular type of optimal prefix"
"code that is commonly used for lossless data compression. The process of finding or using such a"
"code proceeds by means of Huffman coding, an algorithm developed by David A. Huffman while he was a"
"Sc.D. student at MIT, and published in the 1952 paper \"A Method for the Construction of"
"Minimum-Redundancy Codes\".[1]\n"
"The output from Huffman's algorithm can be viewed as a variable-length code table for encoding a"
"source symbol (such as a character in a file). The algorithm derives this table from the estimated"
"probability or frequency of occurrence (weight) for each possible value of the source symbol. As in"
"other entropy encoding methods, more common symbols are generally represented using fewer bits than"
"less common symbols. Huffman's method can be efficiently implemented, finding a code in time linear"
"to the number of input weights if these weights are sorted.[2] However, although optimal among"
"methods encoding symbols separately, Huffman coding is not always optimal among all compression"
"methods - it is replaced with arithmetic coding[3] or asymmetric numeral systems[4] if better"
"compression ratio is required.\n"
;

static const char* const TEXT_2 = 
"Huffman coding uses a specific method for choosing the representation for each symbol, resulting in"
"a prefix code (sometimes called \"prefix-free codes\", that is, the bit string representing some"
"particular symbol is never a prefix of the bit string representing any other symbol). Huffman coding"
"is such a widespread method for creating prefix codes that the term \"Huffman code\" is widely used as"
"a synonym for \"prefix code\" even when such a code is not produced by Huffman's algorithm.\n"
;

static const char* const TEXT_3 = 
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras malesuada enim odio, molestie ornare leo tempor vel. Proin ullamcorper ex id magna volutpat posuere sed at purus. Proin sit amet pharetra nisl. Cras mollis erat ac aliquam pellentesque. Integer vel ligula quis ligula accumsan condimentum. In id molestie nisl. Vestibulum in urna tellus. Nulla semper facilisis dolor eget dictum. Cras vitae pretium massa. Duis a finibus nibh. Sed ultrices nec leo non congue. Donec quis mi metus.\n"
"Sed sed scelerisque lorem. Maecenas laoreet neque vehicula neque aliquet, at volutpat lorem viverra. Vivamus at augue nunc. Curabitur at posuere magna, eu venenatis neque. Mauris cursus pellentesque ipsum ac porta. Pellentesque mattis laoreet mauris, ut blandit odio lobortis vitae. Morbi tincidunt accumsan mi. Aliquam egestas nisl non diam sodales, eu tincidunt lorem pharetra. Duis et augue vitae mauris consequat dictum. Nam sit amet eros faucibus, sagittis justo quis, condimentum orci.\n"
"Vestibulum cursus consectetur risus sed aliquam. Nullam porta nulla in tellus feugiat, at finibus urna rutrum. Integer eget lorem in ex aliquet lobortis ut ut magna. Ut eu lectus id quam imperdiet porttitor. Maecenas eget lectus nec velit consectetur scelerisque. Donec semper, nibh sed viverra elementum, orci orci volutpat ligula, at egestas nibh libero vel ante. Curabitur bibendum ligula blandit dolor volutpat ultricies. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis lorem sit amet porttitor suscipit. Proin sagittis ex et egestas faucibus. Nulla id lacus a diam lacinia fringilla vitae ut nulla.\n"
"Quisque id mi accumsan, pellentesque nibh sit amet, malesuada ex. Sed ultricies dictum pretium. Sed id accumsan mauris. Morbi odio erat, dictum sed rhoncus vel, porta sed tortor. Nulla vestibulum ac dui ac congue. Sed vehicula diam varius ligula rhoncus ultricies. Maecenas ut velit quis tortor rutrum tempor et sed ex.\n"
"Quisque in egestas augue. Praesent mattis nibh ut tempor rhoncus. Nam sed accumsan lorem, a commodo nisl. Mauris eu turpis fringilla, rhoncus orci vitae, placerat diam. Praesent ut viverra justo, a bibendum nisi. Maecenas cursus turpis at eros facilisis vulputate. Nullam ut aliquet quam, eu facilisis nibh. Quisque pretium justo sit amet suscipit lacinia. Cras pulvinar viverra orci eget luctus. Sed eleifend id ante nec ornare. Vivamus varius, neque vitae dictum ullamcorper, libero mi posuere dui, vel auctor nisi quam sed justo. Curabitur et massa sit amet augue porttitor finibus. Ut malesuada lectus non lectus placerat interdum.\n"
"Integer sagittis convallis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus pretium, ex ut tempus congue, eros odio finibus tellus, ut tempus tellus ligula nec felis. Fusce nec gravida augue, nec egestas nisl. Aliquam ultricies efficitur nunc, ut sodales odio condimentum eu. Donec ultricies feugiat erat, nec porta ex elementum eget. Integer ac massa viverra sapien tempus pharetra ut vitae odio. Vestibulum id mauris condimentum, congue sem id, dignissim diam. In nec diam neque. Maecenas suscipit, erat vel tempor hendrerit, erat arcu pharetra dui, non vestibulum mi dui eget arcu. Vivamus vulputate vitae ante id mollis. Mauris ac elementum ante. Vestibulum tristique, leo sed interdum ullamcorper, dolor tellus ultrices metus, at sodales magna enim a ipsum. Vestibulum non est euismod, vestibulum massa eget, facilisis lacus. Morbi placerat erat eu viverra porta. Vestibulum vulputate dolor ac vehicula venenatis.\n"
"Sed a rutrum ligula. Nam porta malesuada sapien vitae ultricies. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur lobortis vestibulum lectus. Aenean gravida accumsan semper. Morbi lacinia odio porttitor pulvinar facilisis. Nunc eget condimentum quam. Sed placerat, dolor quis pharetra viverra, ipsum lacus facilisis ante, vitae mollis nibh ex eget quam. Morbi efficitur sodales nisl quis sagittis.\n"
"Ut fringilla dui in auctor pretium. Integer molestie dolor non tellus accumsan, a cursus tortor aliquet. Sed bibendum massa pretium, posuere lacus quis, ultricies quam. Donec aliquet, libero non tincidunt dictum, nunc augue semper orci, quis auctor massa diam ut velit. Proin dapibus lectus libero, et mattis sapien hendrerit vitae. Nunc a turpis posuere, vulputate nibh id, fermentum justo. Pellentesque vitae lacus congue, commodo erat a, rutrum diam. Praesent pretium nunc nec nulla ullamcorper, at malesuada risus iaculis. Nulla id mauris condimentum, rhoncus augue et, laoreet nibh. Fusce ultrices lacus vel neque molestie dapibus. Integer sed mauris mauris. Duis mattis nisi et libero vehicula, non ultrices ligula egestas. Maecenas vitae finibus elit, in vulputate mi.\n"
"Curabitur dapibus malesuada enim et egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In porttitor vestibulum diam sit amet varius. Vivamus vestibulum erat tortor, sed sodales ante convallis at. Morbi faucibus, est eget venenatis scelerisque, ex dolor congue tortor, vitae sollicitudin metus ligula at justo. Vestibulum efficitur ullamcorper molestie. Donec varius lectus vel ligula dignissim, non gravida nisi dignissim. Curabitur diam nunc, sagittis a diam nec, finibus lobortis orci. Aenean in condimentum erat, in imperdiet enim. Proin tristique, tellus sit amet pretium porttitor, turpis justo molestie mauris, vitae convallis dolor ex eu lectus. Morbi sed dapibus massa.\n"
"Vivamus sem enim, convallis eu nibh quis, convallis convallis leo. Duis faucibus in sem sit amet fringilla. Vestibulum est diam, ornare eget nisl at, viverra auctor magna. Etiam enim eros, tincidunt nec mauris sit amet, fringilla cursus ipsum. Nulla ipsum elit, tristique aliquet quam a, efficitur vehicula enim. Nunc erat elit, fringilla id tempus ac, euismod in arcu. Etiam non justo vel elit imperdiet placerat. Maecenas placerat iaculis rhoncus. Ut urna urna, porta sed dignissim at, fringilla vitae nibh. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc sed lectus et nisl feugiat cursus.\n"
"Phasellus euismod placerat libero, in faucibus sem hendrerit vitae. Morbi placerat iaculis tortor at malesuada. Cras eget sem orci. Nam sit amet tempor magna, tempus consequat diam. Integer ornare velit lacus, ut vehicula odio accumsan nec. Pellentesque quis purus in augue lobortis condimentum. Morbi at mollis nibh. Quisque scelerisque mi nisi, eget porta mi scelerisque at. Sed posuere metus sem, at porttitor leo scelerisque vitae.\n"
"Nunc blandit tincidunt quam, sit amet aliquam lorem tempus ac. Duis efficitur ultrices mi, quis aliquam massa hendrerit non. Morbi euismod vulputate lectus, vel fringilla felis cursus fermentum. Nam accumsan purus ligula, non pretium nisl hendrerit quis. Nulla pulvinar felis magna, in posuere arcu rhoncus sit amet. Nam venenatis efficitur felis, sit amet laoreet lacus tincidunt ac. Ut malesuada blandit efficitur. Proin ac vehicula quam. Nunc viverra euismod ultrices. In sit amet elit turpis. Maecenas nec aliquam eros. Suspendisse eu nibh ac risus vestibulum interdum. Curabitur congue et erat sed porta. Aliquam vitae arcu eu eros tristique luctus quis quis tellus. Donec semper nibh congue, cursus neque et, blandit magna. Vivamus interdum augue at arcu mattis luctus.\n"
"Quisque varius ante quam, eu tempus justo blandit a. Duis tempor arcu vel quam molestie vestibulum. Integer sapien augue, porta posuere leo ac, maximus venenatis quam. Nullam accumsan tellus a lorem tempus lacinia. Nam vel varius nulla. Pellentesque vulputate ligula et quam faucibus tempus. Curabitur id consectetur lorem, porttitor fermentum velit. Integer vitae risus nibh. Phasellus viverra diam ante, in molestie lorem pellentesque at. Sed faucibus turpis ac nisl vulputate commodo.\n"
"Fusce sed tortor non nulla congue accumsan sit amet vitae ipsum. Nullam eu lacinia purus. Suspendisse sodales id turpis sed gravida. Integer turpis justo, viverra a nibh ac, condimentum pretium tellus. Donec et mattis urna. Ut non feugiat odio. Pellentesque fermentum mattis malesuada. Vestibulum at lectus eleifend leo auctor dictum. Ut nec lacus imperdiet, dapibus tortor in, facilisis arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris volutpat justo lacinia felis sagittis, non varius est bibendum. Pellentesque venenatis vel risus sed rutrum. Duis ultricies sodales dolor a tristique. Sed et blandit felis, ullamcorper faucibus magna.\n"
"Duis gravida quam risus, a condimentum nisi sollicitudin eu. Nunc sodales, libero vel mollis iaculis, magna lacus tempus dui, sit amet volutpat velit ex nec nulla. Morbi sit amet egestas ex, sit amet lobortis turpis. Maecenas ultricies, est id volutpat luctus, eros lectus consectetur quam, id cursus lorem justo non lectus. Curabitur sodales iaculis eleifend. Ut posuere lorem non elit posuere, ac venenatis enim sollicitudin. Curabitur vestibulum purus nec blandit placerat. Vivamus congue libero at sem fringilla, dignissim gravida enim elementum. Quisque ultrices malesuada ex, vel mattis eros pellentesque in. Phasellus ut malesuada odio. Nulla quis fermentum mauris. Nulla porta, enim placerat sagittis consequat, dolor eros egestas tortor, a luctus lorem libero eu enim. Nunc porta cursus lacus, convallis maximus nibh faucibus sed. Curabitur non interdum erat.\n"
"In at nunc tellus. Proin sed magna et ipsum accumsan pretium ut eget justo. Sed eleifend, augue vitae faucibus dictum, erat purus dictum neque, a hendrerit justo nisl non orci. Integer dignissim ipsum et viverra interdum. Sed quis urna vel velit mattis tempus. Nunc vel ipsum vel dui blandit varius id eget nibh. Maecenas eget lorem sed nibh dictum ornare. Duis vulputate eget elit id consequat. Suspendisse eu augue hendrerit, interdum ante sed, blandit leo. Integer ipsum lacus, volutpat quis maximus sit amet, fermentum eget augue. Sed malesuada sem sit amet nisl gravida, ac eleifend tellus tempor. Ut sodales, quam ac laoreet finibus, leo dolor fermentum lacus, et egestas nulla lectus ac sem.\n"
"Nunc mollis, leo nec molestie ornare, odio tellus scelerisque dolor, quis interdum leo metus quis elit. Proin porttitor, ante ac vehicula vestibulum, sapien nulla euismod nunc, et eleifend massa lectus in erat. Sed nulla velit, dictum sed dui at, tristique posuere ex. Vestibulum lacinia magna lorem, eget vestibulum elit dignissim sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse odio justo, scelerisque vel ex non, accumsan bibendum urna. Nulla facilisi. Nullam pretium posuere lorem. Praesent auctor efficitur ante, id interdum lectus facilisis sed. Nam commodo consequat ante. Pellentesque id commodo lectus.\n"
"Ut ultricies velit quis augue sagittis suscipit. Proin id vulputate odio, nec tincidunt dui. Suspendisse rhoncus feugiat odio. In ac lacus viverra, varius mauris eu, egestas turpis. Proin vitae justo in neque lobortis pretium. Phasellus porttitor, turpis non gravida pharetra, arcu turpis gravida neque, id eleifend enim eros quis erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec in augue elit. Quisque faucibus odio vitae suscipit interdum. Pellentesque accumsan dapibus magna. Nunc porta placerat magna at sagittis. Nulla eget lectus vel quam pulvinar pulvinar eu in tortor. Nulla scelerisque tellus eu mi facilisis ornare. Maecenas consequat lorem sed consequat semper.\n"
"Ut ante turpis, commodo feugiat neque ac, ultrices porttitor dui. Praesent eleifend massa tincidunt, dignissim ligula ac, feugiat arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris aliquet dui at purus semper pharetra. Morbi sed varius ex, sollicitudin hendrerit orci. In eleifend enim vitae venenatis iaculis. Nam vehicula diam justo, non aliquet ligula accumsan vitae. Nulla placerat, quam sed pellentesque tincidunt, augue felis porta odio, sed mattis tortor purus nec erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;\n"
"Integer tincidunt mauris ut neque facilisis posuere. Mauris vestibulum arcu augue, eget tempus neque cursus a. In id nisi eu lorem rutrum efficitur. Fusce placerat fringilla leo sed placerat. Maecenas pulvinar nisl nec sapien feugiat tincidunt. In hac habitasse platea dictumst. Vestibulum dignissim purus ac est ultrices tristique. Vestibulum facilisis metus enim, quis consequat tellus iaculis et. Vestibulum libero mi, mattis in mauris eu, consectetur ultrices felis. Vestibulum dapibus felis nec nisi efficitur sollicitudin. Donec dolor leo, pharetra sit amet maximus id, rhoncus finibus metus. Donec ut feugiat felis, nec luctus diam.\n"
"Ut non nisi vel lacus viverra consectetur eget eu turpis. Nunc pellentesque nulla quis sem posuere, nec tristique risus sodales. Curabitur aliquet ac neque sit amet tempus. Etiam dictum, turpis sollicitudin egestas tristique, ipsum magna tempor lorem, convallis fringilla erat dui id nibh. Vivamus iaculis congue ex, luctus gravida urna bibendum at. Nunc maximus, ligula in efficitur efficitur, libero felis dictum justo, in sodales magna metus at purus. Quisque non elementum risus. Nulla nec rutrum lectus. Phasellus vel lacinia ex, sit amet rhoncus quam. Suspendisse sit amet accumsan tortor. Nam tincidunt risus at turpis suscipit volutpat. Nunc vel nisl ut enim accumsan pellentesque vel ut sapien. Cras accumsan risus at lorem aliquet, non condimentum mauris cursus. Integer laoreet orci aliquet lacinia vehicula. Cras neque nisl, faucibus non facilisis sit amet, bibendum ut felis. Phasellus porttitor erat ut neque scelerisque mattis.\n"
"Vestibulum sollicitudin commodo leo, vitae commodo quam. Mauris ante dui, ultricies sed lacus non, pharetra egestas erat. Nullam viverra pulvinar commodo. Pellentesque ac massa eget augue congue tristique. Curabitur eu finibus ex. Donec vestibulum, dui sit amet gravida scelerisque, justo lectus ullamcorper ipsum, vel rutrum libero eros nec mi. Aenean fermentum fringilla urna. Sed ornare orci ut dolor ultricies iaculis. Donec aliquet risus in convallis gravida. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam volutpat efficitur bibendum. Sed et lectus dictum, ultrices metus a, sodales nunc. Integer varius sapien nec velit egestas, et aliquet leo condimentum. Duis non ante et augue auctor consectetur. Nullam pulvinar odio et metus rutrum sagittis. Fusce porta volutpat massa in consequat.\n"
"Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam nec tortor a ex laoreet aliquet. Cras ultrices blandit ipsum, efficitur commodo metus. Nam auctor dictum mollis. Nullam eget mauris pulvinar, sollicitudin neque sed, finibus sapien. Curabitur a turpis varius, placerat eros et, fermentum sapien. Maecenas massa elit, viverra cursus magna eget, laoreet eleifend magna. Curabitur rhoncus viverra iaculis. Maecenas porta sem vitae quam faucibus, sit amet condimentum nibh porttitor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n"
"Nulla facilisi. Etiam nisi mi, aliquet eget auctor in, sollicitudin in lectus. Donec congue, leo ac posuere aliquam, urna enim aliquam sapien, a accumsan lacus felis sed tellus. Etiam nulla nisi, porttitor sed hendrerit et, tincidunt nec arcu. Nunc in nunc eu libero placerat pretium vitae vitae turpis. Maecenas vitae massa lobortis, ultrices arcu non, faucibus velit. Nam interdum elit ut lacus facilisis, eget tristique augue posuere. Pellentesque tristique venenatis diam, in viverra orci pellentesque ullamcorper. Donec a velit fermentum, viverra odio quis, hendrerit mi. Suspendisse a egestas nibh. Cras ut massa tortor. Quisque efficitur diam id sodales aliquam. Maecenas id elit accumsan, blandit arcu ac, egestas massa. Sed vulputate vel orci in accumsan. Sed a porta dui. Nunc a leo in ligula scelerisque facilisis nec quis purus.\n"
"Nam ut libero at lorem elementum sagittis. Nulla eu nisl porta, fermentum leo sed, maximus ligula. In bibendum mollis eros eu dignissim. Maecenas egestas risus eu tincidunt dictum. Praesent at lorem ligula. Aenean lobortis augue non feugiat suscipit. Ut mattis felis at ante hendrerit, vel bibendum ante fringilla. Cras molestie libero ac nisl iaculis iaculis. In hac habitasse platea dictumst. Nullam elit libero, vehicula non turpis in, varius lobortis tellus. Suspendisse interdum id dui et bibendum. Proin lectus urna, ultricies et purus a, ornare mollis magna. Fusce vitae lacus eget metus pellentesque blandit. Etiam ullamcorper risus lorem, finibus imperdiet neque vulputate quis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras in ex enim.\n"
"Curabitur enim orci, dignissim in vehicula et, porta sed dui. Suspendisse in nisi nec arcu sagittis sodales. Praesent nunc est, ornare vitae justo et, pellentesque sollicitudin purus. In consectetur fringilla nisi, sed sodales velit varius id. Curabitur lectus lectus, ultricies sed euismod at, vulputate sit amet felis. Phasellus fringilla libero nec posuere eleifend. Morbi eros dui, scelerisque vitae molestie id, laoreet quis ante. Suspendisse pharetra sem eget ipsum ornare sagittis. Donec gravida facilisis arcu non tincidunt. Nunc rhoncus facilisis erat, in mollis ante consectetur id. Curabitur sit amet commodo arcu. Morbi ullamcorper est ac tortor pellentesque fringilla. Vestibulum molestie consequat lorem, et efficitur augue venenatis vel.\n"
"Duis nec faucibus velit, at sagittis felis. Nullam nec eros ultrices, aliquam dolor ut, vulputate neque. Maecenas augue risus, pharetra eget accumsan a, ultrices sit amet orci. Maecenas mattis, enim a aliquet blandit, ex metus tempus ipsum, dignissim sodales quam nulla ac libero. Suspendisse pulvinar eleifend urna, nec laoreet arcu. Sed libero mauris, ornare eget odio at, auctor lobortis metus. Proin euismod, eros in tempus tempus, odio est mollis ipsum, id vulputate mi enim a lorem. Morbi viverra nisi tortor, at suscipit velit semper in. Curabitur tincidunt, ante non cursus pellentesque, ligula nunc suscipit ante, id accumsan erat eros ac mi. Morbi a elit ultricies, vehicula lectus non, tincidunt ex. Curabitur scelerisque lacus vitae nunc ornare, hendrerit consectetur est iaculis.\n"
"Suspendisse potenti. Nunc tempor sodales lectus, sit amet porttitor mauris lobortis quis. Aenean ultrices volutpat elit, at venenatis sem vulputate at. Curabitur iaculis rhoncus diam eget maximus. Fusce libero velit, imperdiet aliquet arcu nec, scelerisque lobortis sem. Aenean et neque sed urna rutrum finibus id sit amet augue. Mauris elit sem, commodo in metus ultricies, semper efficitur turpis.\n"
"Maecenas vehicula, orci quis efficitur efficitur, odio dolor facilisis felis, a pellentesque urna urna et nisl. Integer in quam vel mauris commodo ultrices interdum lobortis purus. Nunc eu urna sapien. In eget magna imperdiet, efficitur quam vitae, elementum orci. Fusce nec sollicitudin ligula. Integer rhoncus at ante eget blandit. Cras quis euismod elit, sit amet bibendum justo. Maecenas id odio egestas, iaculis turpis a, sollicitudin urna. Nunc est est, hendrerit sit amet turpis a, vestibulum sollicitudin felis. Phasellus in lorem varius, sollicitudin enim et, mollis erat. Nunc tincidunt lobortis lorem, a porttitor urna imperdiet at. Quisque pellentesque ligula ac ante molestie, sed laoreet nulla venenatis. Curabitur ultrices commodo magna, eget condimentum tortor hendrerit in. Duis non turpis eu magna consectetur suscipit a quis purus.\n"
"Nunc fermentum orci a quam interdum ultrices. Aenean malesuada egestas justo eu ullamcorper. Quisque in nisl neque. Aliquam vulputate laoreet tellus, ut porta diam vestibulum non. Nunc laoreet, nisl id vestibulum pharetra, dui odio porttitor turpis, sed fringilla orci massa vitae magna. Donec tempus ornare nunc, et eleifend felis imperdiet maximus. Nunc et porta tortor. Cras tellus massa, porta sed quam sit amet, eleifend blandit ante. Vivamus eget est ut justo cursus molestie et id odio. Nullam odio ligula, sollicitudin et erat sed, sodales maximus tellus. Quisque vestibulum lorem in ultricies blandit. Integer sed quam sit amet felis pretium euismod.\n"
"Curabitur blandit nisi eu odio pretium, quis mollis leo tempus. Integer pellentesque mattis urna, et mattis dui placerat at. In vestibulum ante quam, eu condimentum elit mollis in. Praesent nec ante mattis, sagittis dolor id, ultricies justo. Phasellus ut laoreet nisl. Etiam pellentesque sollicitudin turpis, id mollis lorem pharetra vitae. Phasellus blandit mi eu luctus vestibulum. Donec ultrices nunc ut placerat faucibus. In quam augue, vulputate nec ultricies at, pellentesque vulputate est. Donec in nulla quis neque eleifend lobortis. Fusce vel est vitae mi pretium eleifend. Etiam vulputate dapibus lacus. Suspendisse non consequat risus, nec fringilla lacus. Donec quis cursus arcu. Pellentesque neque libero, egestas at condimentum ornare, egestas vel velit.\n"
"Etiam id fringilla erat, nec molestie quam. Suspendisse venenatis massa eu massa gravida, placerat fermentum justo vestibulum. Nulla faucibus nulla ac fermentum mattis. Suspendisse potenti. Maecenas tempus nulla a libero varius accumsan. Duis ultrices volutpat ullamcorper. Sed dictum euismod magna, ac placerat massa porta eu. Aenean efficitur a justo in tincidunt.\n"
"Aenean eleifend efficitur ante consectetur pulvinar. Suspendisse non massa pretium, posuere arcu a, commodo ante. Nulla facilisi. Mauris efficitur nunc enim, tincidunt tincidunt metus vulputate in. Curabitur eleifend nisi arcu, ac ultricies elit aliquam id. Quisque pellentesque ex non purus tempor, ut laoreet urna rhoncus. Donec et dui ut eros porttitor commodo. Integer lacinia luctus leo, vel mattis arcu iaculis ac. Curabitur maximus euismod leo, eget sollicitudin urna commodo eget. Donec consectetur ornare tristique. Suspendisse ut nibh purus. Mauris eu quam ac sapien lacinia vestibulum id quis urna. Donec ultrices magna non massa scelerisque, eget commodo felis condimentum. Duis gravida ornare turpis sed porttitor.\n"
"Mauris consectetur dui eget eros tempus lacinia. Morbi tristique, dolor a luctus tempor, ante velit ullamcorper dui, vel posuere orci enim vitae leo. Pellentesque sed ligula hendrerit, vestibulum nisl fermentum, eleifend risus. Duis nec malesuada sem, sed ornare enim. Duis fermentum, lorem accumsan imperdiet fringilla, ipsum eros auctor massa, ultrices laoreet elit nulla et diam. Suspendisse potenti. Donec venenatis nulla sodales nunc semper dignissim. Praesent sed diam a augue fermentum congue eu quis mauris. Curabitur molestie placerat pretium. Mauris posuere porta dolor, malesuada consequat turpis fringilla eget.\n"
"Morbi a sapien a elit volutpat faucibus. Suspendisse non massa neque. Pellentesque ornare interdum sodales. Nullam viverra, eros quis vehicula tincidunt, velit libero tristique est, at hendrerit urna enim at ante. Nam luctus ex ut lorem congue, ut finibus nibh suscipit. Pellentesque in sem vitae erat commodo condimentum sed sit amet metus. Integer dolor libero, facilisis sed rutrum sed, pharetra ac ligula. Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n"
"Nunc mollis ipsum a lorem convallis, in accumsan orci volutpat. Donec ut sapien et mi vehicula dictum nec a tortor. Nulla vel urna dictum, iaculis lacus sit amet, blandit velit. Aenean nisi augue, dignissim at urna eu, aliquam sodales nunc. In hac habitasse platea dictumst. Sed dictum iaculis justo vel sagittis. In tincidunt metus nec dignissim bibendum. Morbi facilisis justo id nisl sodales feugiat. Donec ut leo rutrum urna eleifend maximus.\n"
"Mauris ac congue erat. Nam tellus enim, pulvinar vel pretium euismod, ornare feugiat ex. Morbi elementum pulvinar posuere. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc est tellus, dignissim vel gravida in, aliquet non magna. Vivamus feugiat, nisi quis laoreet porttitor, orci augue lobortis nibh, a mattis nibh augue consectetur odio. Aenean ultricies eget sapien nec rhoncus.\n"
"Morbi eget felis quis metus porttitor mattis. Duis dapibus arcu et arcu euismod, vel ultricies ante suscipit. Praesent posuere viverra eros ut bibendum. Aliquam vehicula rutrum eleifend. Proin sit amet semper ante, id dignissim libero. Ut vitae libero neque. Integer sollicitudin purus at augue ullamcorper commodo. Pellentesque sit amet tellus a lectus bibendum congue. Sed fermentum maximus diam nec dapibus. Nunc ut mi in massa scelerisque ultricies eget id est. Aenean pretium erat id vulputate condimentum. Praesent et turpis efficitur, pharetra diam id, facilisis nisl. Nulla dignissim elementum hendrerit. Maecenas ut justo neque. Mauris vestibulum mollis finibus. Integer lacinia elementum nisl, ac ornare urna luctus quis.\n"
"Vivamus ut elit vulputate, tincidunt enim sit amet, pellentesque quam. Duis at efficitur libero. Nulla imperdiet porta rhoncus. Pellentesque accumsan semper libero at pharetra. Curabitur malesuada ornare ultrices. Aliquam in nisi vel sapien sodales efficitur eget a arcu. Fusce interdum eros nec quam suscipit molestie. Fusce lacinia metus vitae suscipit aliquam. Nam mi nisi, ornare in quam id, lobortis elementum tellus. Phasellus aliquam id magna quis fringilla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi non purus facilisis, pellentesque urna sit amet, condimentum ante. Duis posuere magna sed diam gravida placerat.\n"
"Phasellus lacus nulla, scelerisque vel nulla at, eleifend rhoncus enim. Phasellus sit amet maximus justo, id aliquet est. Aliquam ullamcorper at lorem nec placerat. Vestibulum ac blandit est. Donec eros massa, vulputate non fermentum quis, volutpat eget urna. Maecenas tempor ultrices lorem, vitae ultrices nunc semper in. Morbi ac mi tortor. Fusce faucibus felis ut hendrerit facilisis. Nunc nec risus cursus, molestie massa et, condimentum dolor. In turpis nulla, tempus sit amet nisl non, euismod auctor odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n"
"Donec vehicula odio sed dolor cursus, in varius ante lacinia. Praesent in arcu suscipit, convallis ante sit amet, imperdiet enim. Curabitur tempus justo erat. Fusce nunc nunc, ultrices in leo ac, ultricies congue risus. Duis quis tellus augue. Vestibulum augue neque, molestie in augue quis, imperdiet pulvinar nisi. Nunc rutrum risus eu lacus tempus porta. Vestibulum tempor sed odio vel pretium. Nam consectetur libero metus, laoreet mollis libero porta in. Nam nec risus non ligula suscipit dignissim ut eget felis. Maecenas ultricies ullamcorper mollis. Phasellus ligula elit, rhoncus eget velit eu, bibendum tincidunt leo. Suspendisse at rutrum sapien, non tincidunt ligula. Nunc eget nunc sit amet neque tincidunt fringilla. Cras rutrum, nisl a dapibus efficitur, libero lacus tincidunt velit, ac congue nulla urna at nulla.\n"
"Mauris pulvinar maximus est in tincidunt. Donec dignissim sagittis turpis, id sagittis enim volutpat at. Duis auctor ipsum et pharetra pellentesque. Fusce porta erat vel facilisis lobortis. Curabitur quis lectus et dolor aliquam convallis. Duis tempor est justo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In molestie risus vel elit fringilla aliquam. Cras dui nisi, feugiat tempus mi dapibus, gravida vehicula leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas placerat vitae est ac lobortis. In hac habitasse platea dictumst.\n"
"Cras sit amet velit volutpat, vulputate sem vitae, blandit arcu. Nullam tristique, felis vel vestibulum sodales, ipsum ipsum vulputate sapien, eu finibus dui quam ac augue. Proin convallis augue porttitor dolor semper, at cursus nisi cursus. Suspendisse potenti. Mauris non libero elementum, aliquet diam eu, sollicitudin magna. Suspendisse sit amet augue tortor. Praesent non sapien blandit, vehicula diam.\n"
;
